In [109]:
import numpy as np

s_box = np.array([10, 4, 3, 11, 8, 14, 2, 12, 5, 7, 6, 15, 0, 1, 9, 13], dtype=np.uint8)
n = 16
s_box

array([10,  4,  3, 11,  8, 14,  2, 12,  5,  7,  6, 15,  0,  1,  9, 13],
      dtype=uint8)

In [115]:
A = np.arange(n).repeat(n).reshape(n, n)
A

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
       [ 6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6],
       [ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7],
       [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8],
       [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
       [13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,

In [147]:
difference_table = s_box[A ^ np.arange(16)] ^ s_box
difference_table

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [14, 14,  8,  8,  6,  6, 14, 14,  2,  2,  9,  9,  1,  1,  4,  4],
       [ 9, 15,  9, 15, 10,  2, 10,  2,  3,  8,  3,  8,  9, 12,  9, 12],
       [ 1,  7,  7,  1,  4, 12, 12,  4, 10,  1,  1, 10, 13,  8,  8, 13],
       [ 2, 10,  1,  7,  2, 10,  1,  7,  5,  6, 15,  2,  5,  6, 15,  2],
       [ 4, 12, 15,  9, 12,  4,  9, 15,  4,  7, 11,  6,  7,  4,  6, 11],
       [ 8,  8, 11,  5, 11,  5,  8,  8, 12, 10,  6, 14,  6, 14, 12, 10],
       [ 6,  6, 13,  3,  3, 13,  6,  6,  8, 14,  7, 15, 15,  7, 14,  8],
       [15,  3,  5,  4,  8, 15, 11,  1, 15,  3,  5,  4,  8, 15, 11,  1],
       [13,  1, 12, 13,  9, 14, 15,  5,  1, 13, 13, 12, 14,  9,  5, 15],
       [12, 11,  6, 12,  1,  3,  2, 13,  6, 12, 12, 11,  2, 13,  1,  3],
       [ 5,  2,  4, 14,  5,  7,  3, 12, 14,  4,  2,  5, 12,  3,  7,  5],
       [10,  5, 10,  6, 13,  9,  4,  3, 13,  9,  4,  3, 10,  5, 10,  6],
       [11,  4, 14,  2, 15, 11, 13, 10, 11, 15, 10,

In [152]:
differential_cryptanalysis_table = np.zeros((n, n), dtype=np.uint8)
for diff in range(n):
    vlaues, counts = np.unique(difference_table[diff], return_counts=True)
    differential_cryptanalysis_table[diff][vlaues] = counts
differential_cryptanalysis_table

array([[16,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  2,  0,  2,  0,  2,  0,  2,  2,  0,  0,  0,  0,  4,  0],
       [ 0,  0,  2,  2,  0,  0,  0,  0,  2,  4,  2,  0,  2,  0,  0,  2],
       [ 0,  4,  0,  0,  2,  0,  0,  2,  2,  0,  2,  0,  2,  2,  0,  0],
       [ 0,  2,  4,  0,  0,  2,  2,  2,  0,  0,  2,  0,  0,  0,  0,  2],
       [ 0,  0,  0,  0,  4,  0,  2,  2,  0,  2,  0,  2,  2,  0,  0,  2],
       [ 0,  0,  0,  0,  0,  2,  2,  0,  4,  0,  2,  2,  2,  0,  2,  0],
       [ 0,  0,  0,  2,  0,  0,  4,  2,  2,  0,  0,  0,  0,  2,  2,  2],
       [ 0,  2,  0,  2,  2,  2,  0,  0,  2,  0,  0,  2,  0,  0,  0,  4],
       [ 0,  2,  0,  0,  0,  2,  0,  0,  0,  2,  0,  0,  2,  4,  2,  2],
       [ 0,  2,  2,  2,  0,  0,  2,  0,  0,  0,  0,  2,  4,  2,  0,  0],
       [ 0,  0,  2,  2,  2,  4,  0,  2,  0,  0,  0,  0,  2,  0,  2,  0],
       [ 0,  0,  0,  2,  2,  2,  2,  0,  0,  2,  4,  0,  0,  2,  0,  0],
       [ 0,  0,  2,  0,  2,  0,  0,  0,  0,  0,  2,

In [151]:
np.unique(difference_table[0], return_counts=True)

(array([0], dtype=uint8), array([16], dtype=int64))