In [1]:
import numpy as np

s_box = np.array([10, 4, 3, 11, 8, 14, 2, 12, 5, 7, 6, 15, 0, 1, 9, 13], dtype=np.uint8)
n = 16
s_box

array([10,  4,  3, 11,  8, 14,  2, 12,  5,  7,  6, 15,  0,  1,  9, 13],
      dtype=uint8)

In [2]:
linear_equations = np.arange(n**2)
linear_equations = linear_equations[
    np.asarray(linear_equations % n, dtype=bool) & (linear_equations >= n)
]  # filter out equations with no variables on each side
linear_equations

array([ 17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
        30,  31,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  49,  50,  51,  52,  53,  54,  55,  56,  57,
        58,  59,  60,  61,  62,  63,  65,  66,  67,  68,  69,  70,  71,
        72,  73,  74,  75,  76,  77,  78,  79,  81,  82,  83,  84,  85,
        86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  97,  98,  99,
       100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 113,
       114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
       127, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
       141, 142, 143, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
       155, 156, 157, 158, 159, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 177, 178, 179, 180, 181, 182,
       183, 184, 185, 186, 187, 188, 189, 190, 191, 193, 194, 195, 196,
       197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 20

In [3]:
plaintext_ciphertext_sequences = s_box + np.arange(n) * n
plaintext_ciphertext_sequences

array([ 10,  20,  35,  59,  72,  94,  98, 124, 133, 151, 166, 191, 192,
       209, 233, 253])

In [4]:
approximations = (
    linear_equations.repeat(n).reshape(-1, n) & plaintext_ciphertext_sequences
)
approximations

array([[  0,  16,   1, ...,  17,   1,  17],
       [  2,  16,   2, ...,  16,   0,  16],
       [  2,  16,   3, ...,  17,   1,  17],
       ...,
       [  8,  20,  33, ..., 209, 233, 253],
       [ 10,  20,  34, ..., 208, 232, 252],
       [ 10,  20,  35, ..., 209, 233, 253]])

In [5]:
state = np.zeros(approximations.shape, dtype=bool)
for i in range(n):
    state ^= np.asarray((approximations // 2**i) % 2, dtype=bool)

state

array([[False,  True,  True, ..., False,  True, False],
       [ True,  True,  True, ...,  True, False,  True],
       [ True,  True, False, ..., False,  True, False],
       ...,
       [ True, False, False, ..., False,  True,  True],
       [False, False, False, ...,  True, False, False],
       [False, False,  True, ..., False,  True,  True]])

In [6]:
true_equations = n - state.sum(axis=1)
biases = np.abs(true_equations / n - 0.5)
biases

array([0.125, 0.   , 0.125, 0.25 , 0.125, 0.   , 0.125, 0.125, 0.   ,
       0.125, 0.   , 0.125, 0.   , 0.125, 0.25 , 0.125, 0.125, 0.   ,
       0.   , 0.125, 0.125, 0.   , 0.125, 0.25 , 0.25 , 0.125, 0.125,
       0.   , 0.   , 0.125, 0.   , 0.125, 0.125, 0.   , 0.25 , 0.125,
       0.125, 0.25 , 0.   , 0.125, 0.125, 0.   , 0.   , 0.125, 0.125,
       0.125, 0.25 , 0.125, 0.125, 0.   , 0.125, 0.   , 0.125, 0.   ,
       0.125, 0.   , 0.25 , 0.125, 0.   , 0.125, 0.   , 0.   , 0.25 ,
       0.125, 0.125, 0.125, 0.125, 0.   , 0.25 , 0.   , 0.   , 0.125,
       0.125, 0.125, 0.125, 0.   , 0.125, 0.125, 0.125, 0.125, 0.25 ,
       0.25 , 0.   , 0.   , 0.125, 0.125, 0.125, 0.125, 0.   , 0.   ,
       0.125, 0.125, 0.25 , 0.125, 0.   , 0.   , 0.125, 0.125, 0.   ,
       0.25 , 0.125, 0.   , 0.125, 0.125, 0.   , 0.25 , 0.125, 0.125,
       0.125, 0.125, 0.25 , 0.   , 0.125, 0.125, 0.   , 0.   , 0.   ,
       0.   , 0.125, 0.125, 0.125, 0.125, 0.   , 0.125, 0.25 , 0.   ,
       0.125, 0.   ,

In [7]:
ordering = biases.argsort()[::-1]
linear_equations[ordering], true_equations[ordering]

(array([149, 168, 231,  53, 173, 225, 223, 122, 219, 115,  66,  76, 103,
         83, 102, 188, 203, 190,  89, 129,  56, 196,  20,  31, 254, 157,
        134, 242,  41,  42, 148, 100, 101, 107, 146, 145,  99,  98, 143,
        142, 106, 137, 130, 108, 109, 126, 114, 116, 119, 120, 133, 132,
         95, 131, 123, 125, 113, 255,  94,  34,  50,  47,  44,  43,  40,
         38,  37,  33,  54,  30,  28,  26,  24,  23,  21,  19,  51,  55,
         93,  74,  92,  87,  86, 151,  84,  79,  77,  72,  58,  70,  68,
         67,  65,  63,  62,  59,  85, 136, 205, 217, 215, 214, 211, 210,
        206, 202, 201, 198, 197, 194, 193, 187, 186, 185, 184, 216, 220,
        182, 221, 253, 251, 249, 247, 245, 243, 241, 239, 238, 237, 236,
        235, 234, 233, 232, 183,  17, 159, 164, 163, 171, 174, 169, 172,
        166, 154, 153, 161, 180, 181, 156, 135, 162,  45,  46, 230,  49,
        139,  52, 229, 228, 227, 226,  57, 138, 110, 140,  27,  18, 252,
         22, 250, 147,  25, 248, 155,  39,  29, 246